// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jatjscatquakhmfyqwhz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImphdGpzY2F0cXVha2htZnlxd2h6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzMDI4MDgsImV4cCI6MjA2NDg3ODgwOH0.5x6wxpW2JgkHccqIo7hVS7xqOPs2GQaCFoFugKQuVnw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);